import type { Lesson } from '@/data/types';

export const lesson10: Lesson = {
  "slug": "records",
  "number": 10,
  "title": "Records & Value Equality",
  "objective": "Model immutable data with records, getting value-based equality, with-expressions, and concise positional syntax for free.",
  "blocks": [
    {
      "kind": "lead",
      "text": "Most of the data your programs move around — an API request, a row from the database, a money value, a coordinate — is just **data**: a bag of values you want to compare, copy, and never accidentally mutate. C# records exist precisely for this, and once you see them you will reach for them constantly."
    },
    {
      "kind": "teachingNotes",
      "items": [
        "Anchor everything to the question *\"is this data, or is this a thing with identity and behavior?\"* That single question drives the record-vs-class decision for the rest of the course.",
        "Python students arrive with `@dataclass` and `NamedTuple` muscle memory. Lean on that analogy hard for value equality and `with`, but make the reference-type gotcha explicit — a `record class` is still heap-allocated and passed by reference even though it *compares* by value.",
        "Run the equality demo live if you can. Watching `==` return `True` for two separately-constructed records is the moment it clicks. Then show the same code with `class` returning `False` and let the surprise land.",
        "Defer deep immutability/threading discussion — just plant the flag that immutable data is easier to reason about. The payoff lands in later lessons on concurrency and DI.",
        "Common student error to pre-empt: thinking `record` means immutable. It does not. Immutability comes from `init`/positional params, not from the keyword.",
        "A compile-error trap students WILL hit: in a top-level-statements file, every type declaration (including a `record`) must come **after** the statements. Put your record at the bottom of `Program.cs`, or in its own file. If they declare the record first, they get CS8803 (\"Top-level statements must precede namespace and type declarations\"). Show this on purpose once.",
        "Worth mentioning for the curious: records implement `IEquatable<T>` and the generated equality is *sealed by type* — a `Manager` record is never equal to an `Employee` record even with identical members, because the synthesized `Equals` checks `EqualityContract`. That's why record inheritance equality behaves correctly. You don't need to teach the mechanism, just that it's there and correct."
      ]
    },
    {
      "kind": "paragraph",
      "text": "In Python you reach for `@dataclass(frozen=True)` or a `NamedTuple` when you want a small, comparable, copy-friendly data holder without writing `__init__`, `__eq__`, `__hash__`, and `__repr__` by hand. C#'s answer is the **record**. Declaring one line gets you a constructor, value-based equality, a readable `ToString`, deconstruction, and a clean way to make modified copies — all generated by the compiler, all correct."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The one-liner that does everything",
      "id": "positional-records"
    },
    {
      "kind": "paragraph",
      "text": "Here is a **positional record** — the most concise form. The parameters in parentheses are the *positional parameters*; for a record (unlike a class) the compiler turns each one into a `public` **init-only property**. `init` means you can set it when you construct the object but never again, so the object is immutable after creation."
    },
    {
      "kind": "callout",
      "tone": "note",
      "title": "Where the record declaration goes",
      "text": "These examples use **top-level statements** (no explicit `Main`). The rule the compiler enforces: all your executable statements come **first**, and every type declaration — including a `record` — must come **after** them in the file. Declaring the record before the statements is a real compile error (CS8803: *\"Top-level statements must precede namespace and type declarations\"*). So the record sits at the **bottom** of `Program.cs` below. In a larger project you'd usually give each record its own file and this never comes up."
    },
    {
      "kind": "code",
      "language": "csharp",
      "filename": "Program.cs",
      "code": "// Target .NET 10 / C# 14, top-level statements.\n// Statements first; the record type is declared at the bottom of the file.\n\nvar coffee = new Money(4.50m, \"USD\");\nvar alsoCoffee = new Money(4.50m, \"USD\");\n\nConsole.WriteLine(coffee);                 // compiler-generated ToString\nConsole.WriteLine(coffee == alsoCoffee);   // value equality, not reference\nConsole.WriteLine(coffee.Amount);          // read the init property\n\n// Deconstruction for free — like Python tuple unpacking.\nvar (amount, currency) = coffee;\nConsole.WriteLine($\"{amount} {currency}\");\n\n// One line. PascalCase the positional params — they become public init properties.\npublic record Money(decimal Amount, string Currency);"
    },
    {
      "kind": "output",
      "label": "Console output",
      "output": "Money { Amount = 4.50, Currency = USD }\nTrue\n4.50\n4.50 USD"
    },
    {
      "kind": "paragraph",
      "text": "Notice what you did **not** write: no constructor body, no `Equals`, no `GetHashCode`, no `ToString`, no deconstructor. The single line `public record Money(decimal Amount, string Currency);` generated all of it. If you wrote the equivalent as a hand-rolled class with correct equality, it would be roughly forty lines — and you'd have to remember to update them every time you add a field."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Value equality vs reference equality",
      "id": "value-equality"
    },
    {
      "kind": "paragraph",
      "text": "This is the headline feature, so let's make the contrast concrete. A plain `class` compares by **reference**: `a == b` is true only when `a` and `b` are literally the same object in memory. A `record` compares by **value**: `a == b` is true when every member is equal, regardless of whether they're the same instance. This mirrors the difference between a Python regular class (identity by default) and a frozen `@dataclass` (which generates `__eq__`)."
    },
    {
      "kind": "twoColumn",
      "cards": [
        {
          "title": "class — reference equality",
          "items": [
            "`==` and `Equals` compare object identity (same heap reference).",
            "Two separately-constructed instances with identical data are **not** equal.",
            "`GetHashCode` is identity-based; works in dictionaries but distinct instances hash differently.",
            "Right default for **entities**: a `Customer` is the same customer because of its Id, not because every field matches.",
            "You can opt in to value equality by overriding `Equals`/`GetHashCode`/`==` manually."
          ]
        },
        {
          "title": "record — value equality",
          "items": [
            "`==`, `Equals`, and `GetHashCode` compare **all** members, generated by the compiler.",
            "Two separately-constructed instances with identical data **are** equal.",
            "Two equal records always produce the same hash code, so they work as dictionary keys and set members.",
            "Right default for **values/DTOs**: a `Money(4.50, \"USD\")` is interchangeable with any other `Money(4.50, \"USD\")`.",
            "Still a reference type (`record class`) — heap-allocated, passed by reference."
          ]
        }
      ]
    },
    {
      "kind": "examples",
      "intro": "The exact same data, modeled as a class versus a record. Watch the equality result flip:",
      "examples": [
        {
          "label": "As a class — reference equality (False)",
          "code": "var a = new PointC { X = 1, Y = 2 };\nvar b = new PointC { X = 1, Y = 2 };\nConsole.WriteLine(a == b);            // different objects\nConsole.WriteLine(ReferenceEquals(a, b));\n\npublic class PointC\n{\n    public int X { get; init; }\n    public int Y { get; init; }\n}",
          "output": "False\nFalse"
        },
        {
          "label": "As a record — value equality (True)",
          "code": "var a = new PointR(1, 2);\nvar b = new PointR(1, 2);\nConsole.WriteLine(a == b);            // same values\nConsole.WriteLine(ReferenceEquals(a, b));\n\npublic record PointR(int X, int Y);",
          "output": "True\nFalse"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Look closely at the record case: `a == b` is `True` but `ReferenceEquals(a, b)` is `False`. That pair of lines is the whole lesson in miniature — same **values**, different **objects**. The record compares what's *inside*; reference equality still asks whether they're literally the same instance on the heap."
    },
    {
      "kind": "callout",
      "tone": "warn",
      "title": "\"record\" does not mean \"immutable\"",
      "text": "The most common beginner trap: assuming a record is automatically immutable. It is not. `public record Person { public string Name { get; set; } }` has a **mutable** `set` and can be reassigned any time. Immutability comes from `init` or from positional parameters, **not** from the `record` keyword. Likewise, `record` is still a *reference type* — it lives on the heap and is passed by reference; only its **equality** is value-based. Reach for `init`/positional syntax when you want true immutability."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "with-expressions: copy, then change one thing",
      "id": "with-expressions"
    },
    {
      "kind": "paragraph",
      "text": "If a record is immutable, how do you ever \"change\" it? You don't — you make a **copy** with some members replaced. That's a `with` expression, and it's called *non-destructive mutation*: the original is untouched, you get a new object. This is the same idea as Python's `dataclasses.replace(obj, field=value)`, but it's first-class syntax in C#."
    },
    {
      "kind": "code",
      "language": "csharp",
      "filename": "Program.cs",
      "code": "var placed = new Order(\"A-1001\", \"Placed\", 79.00m);\n\n// Copy 'placed', change only Status. 'placed' is never mutated.\nvar shipped = placed with { Status = \"Shipped\" };\n\nConsole.WriteLine(placed);\nConsole.WriteLine(shipped);\nConsole.WriteLine(ReferenceEquals(placed, shipped));\n\npublic record Order(string Id, string Status, decimal Total);"
    },
    {
      "kind": "output",
      "label": "Console output",
      "output": "Order { Id = A-1001, Status = Placed, Total = 79.00 }\nOrder { Id = A-1001, Status = Shipped, Total = 79.00 }\nFalse"
    },
    {
      "kind": "paragraph",
      "text": "This is the everyday pattern in real backends: an order moves through states (`Placed` -> `Shipped` -> `Delivered`) by producing a new immutable snapshot at each step rather than mutating a shared object. No one can change `placed` out from under you, which makes the code far easier to reason about — especially across threads or in event-sourced systems where each state transition is a stored fact."
    },
    {
      "kind": "callout",
      "tone": "note",
      "title": "with does a shallow copy",
      "text": "A `with` expression copies member values directly. For value members (`int`, `string`, other records) that's exactly what you want. But if a record holds a **mutable reference** like a `List<T>`, the copy shares the *same* list instance — mutating it affects both objects. Keep records built from immutable members (other records, `ImmutableArray<T>`, `IReadOnlyList<T>`) to avoid surprises."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "init properties and the full property body",
      "id": "init-properties"
    },
    {
      "kind": "paragraph",
      "text": "Positional syntax is the concise option, but you can also write a record with an explicit body — useful when you want validation, computed members, or a mix of required and optional data. The key tool is the `init` accessor: settable during object initialization, read-only forever after. Records and classes both support `init`; it's the idiomatic way to express \"set once at construction.\""
    },
    {
      "kind": "code",
      "language": "csharp",
      "filename": "Program.cs",
      "code": "var c = new Customer { Email = \"ada@contoso.com\" };\nConsole.WriteLine(c);\nConsole.WriteLine(c.Domain);\n\n// c.Email = \"x\";   // compile error: init-only, cannot assign after construction\nvar renamed = c with { DisplayName = \"Ada L.\" };\nConsole.WriteLine(renamed);\n\npublic record Customer\n{\n    // 'required' forces the caller to set it; 'init' locks it afterward.\n    public required string Email { get; init; }\n    public string DisplayName { get; init; } = \"Anonymous\";\n\n    // Computed property — derived, never stored or set.\n    public string Domain => Email.Split('@')[1];\n}"
    },
    {
      "kind": "output",
      "label": "Console output",
      "output": "Customer { Email = ada@contoso.com, DisplayName = Anonymous, Domain = contoso.com }\ncontoso.com\nCustomer { Email = ada@contoso.com, DisplayName = Ada L., Domain = contoso.com }"
    },
    {
      "kind": "callout",
      "tone": "warn",
      "title": "ToString prints computed properties too",
      "text": "Look carefully at the first output line: it includes `Domain = contoso.com`, even though `Domain` is a *computed* expression-bodied property you never set. A record's generated `ToString` prints **every public property it can read**, computed ones included — so derived members show up in logs automatically. That's usually handy, but be deliberate: if a computed property is expensive or sensitive (a decrypted value, a database round-trip), it will run every time the record is `ToString`'d or logged. Keep computed members on records cheap and safe to evaluate."
    },
    {
      "kind": "callout",
      "tone": "tip",
      "title": "Validate at construction with C# 14's field keyword",
      "text": "When you need a setter that *checks* a value, C# 14's `field` keyword lets you write validation without declaring a backing field by hand: `public string Currency { get; init => field = value?.ToUpperInvariant() ?? throw new ArgumentNullException(nameof(value)); }`. The `field` keyword refers to the compiler-generated backing field directly (pair it with `required` to satisfy non-nullable analysis). This keeps records immutable **and** guaranteed-valid from the moment they exist — the best of both worlds for domain values like `Money`, `Email`, or `IsoDate`."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "record struct: value equality without the heap",
      "id": "record-struct"
    },
    {
      "kind": "paragraph",
      "text": "By default `record` means `record class` — a reference type. When you write `record struct`, you get a **value type**: it's copied by value (the whole thing, not a reference) and typically lives on the stack, avoiding a heap allocation. It still gives you compiler-generated value equality and `ToString`. Use it for **small** (a few fields), immutable, value-semantic data where you create lots of instances and want to minimize allocations — coordinates, sizes, small money/measurement types."
    },
    {
      "kind": "examples",
      "intro": "A record struct mirrors a record class for equality, but is a value type. Mark positional record structs readonly to keep them immutable:",
      "examples": [
        {
          "label": "readonly record struct",
          "code": "var p1 = new Point(3, 4);\nvar p2 = new Point(3, 4);\nConsole.WriteLine(p1 == p2);   // value equality\nConsole.WriteLine(p1);\n\nvar moved = p1 with { X = 5 };  // 'with' works here too\nConsole.WriteLine(moved);\n\npublic readonly record struct Point(int X, int Y);",
          "output": "True\nPoint { X = 3, Y = 4 }\nPoint { X = 5, Y = 4 }"
        }
      ]
    },
    {
      "kind": "callout",
      "tone": "warn",
      "title": "Don't store a record struct as object",
      "text": "Assigning a value type (including a `record struct`) to an `object` or a non-generic interface reference silently copies it onto the heap — that's **boxing**, and it erases the allocation savings that made you choose a struct. Also, keep record structs *small*: a large struct is expensive to copy around on every assignment and method call. When in doubt between a big struct and a class, choose the class."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When to use a record (and when not to)",
      "id": "when-to-use"
    },
    {
      "kind": "list",
      "items": [
        "**DTOs and API models** — request/response bodies, view models. They're data in transit: value equality and `with` are exactly right, and immutability prevents accidental mutation after deserialization.",
        "**Domain value objects** — `Money`, `DateRange`, `EmailAddress`, `Coordinate`. These are defined entirely by their values; two `Money(10, \"USD\")` are interchangeable. (Add validation with `init` + the `field` keyword.)",
        "**Events and messages** — in event-driven and event-sourced systems, each event is an immutable fact. Records model that perfectly and copy cheaply with `with`.",
        "**Configuration and options objects** — read once at startup, never mutated. `init` properties enforce that.",
        "**Reach for a class instead** when the type has **identity and behavior**: an EF Core entity like `Customer` (same customer by Id, not by all fields), a service with injected dependencies, or anything with meaningful methods and a lifecycle. Reference equality is the correct default there."
      ]
    },
    {
      "kind": "callout",
      "tone": "tip",
      "title": "The decision rule architects actually use",
      "text": "Ask: **is this data, or a thing?** Data that is defined by its values and shouldn't change after creation -> `record` (or `readonly record struct` if it's small and you allocate many). A *thing* with identity, dependencies, and behavior that evolves over its lifetime -> `class`. This single question resolves the vast majority of real-world cases, and it's a strong, concise answer in an interview."
    },
    {
      "kind": "keyTakeaways",
      "items": [
        "A **record** generates value equality, `ToString`, deconstruction, and copy support for you — C#'s answer to Python's frozen `@dataclass`/`NamedTuple`.",
        "**Value equality** (`==` compares all members) is the headline difference from a `class`, whose `==` compares object identity. `a == b` can be `True` while `ReferenceEquals(a, b)` is `False`.",
        "**Positional records** (`record Money(decimal Amount, string Currency)`) turn parameters into `public init` properties — concise and immutable.",
        "**`with` expressions** give non-destructive mutation: copy the record, replace a few members, leave the original untouched (shallow copy — keep members immutable).",
        "A record's generated `ToString` prints **all** public properties, **including computed ones** — great for logs, but keep computed members cheap and safe.",
        "`record` does **not** mean immutable and is still a **reference type**; immutability comes from `init`/positional params, and `record struct` gives you a value type for small data.",
        "Use records for **DTOs, domain values, events, and config**; use classes for **entities and services** with identity and behavior. The rule: *is it data, or a thing?*"
      ]
    }
  ]
};
